//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDatLichSanBong
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanBong
    {
        public int SanID { get; set; }
        public string TenSan { get; set; }
        public string GhiChu { get; set; }
    }
}
